export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listing',
    route: '/listing',
    description: 'Verified businesses and services.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classified',
    route: '/classified',
    description: 'Local offers, jobs, and deals.',
    contentType: 'classified',
    enabled: false,
  },
  {
  key: 'article',
  label: 'Article',
  route: '/article',
  description: 'Curated article content.',
  contentType: 'article',
  enabled: true,
},
  {
    key: 'image',
    label: 'Image',
    route: '/image',
    description: 'Photo essays and scenes from the road.',
    contentType: 'image',
    enabled: true,
  },
  {
    key: 'profile',
    label: 'Profile',
    route: '/profile',
    description: 'Creator and business profiles.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Curated bookmarks and resources.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Comment',
    route: '/blog',
    description: 'Commentary and response posts.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF',
    route: '/pdf',
    description: 'PDF resources and downloads.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organization',
    route: '/team',
    description: 'Organization profiles and directories.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/image-sharing',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
