export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Business Listings',
    route: '/listings',
    description: 'Verified businesses and services.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Classifieds',
    route: '/classifieds',
    description: 'Local offers, jobs, and deals.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Stories',
    route: '/articles',
    description: 'Long-form travel stories, routes, and essays.',
    contentType: 'article',
    enabled: true,
  },
  {
    key: 'image',
    label: 'Field Photos',
    route: '/image-sharing',
    description: 'Photo essays and scenes from the road.',
    contentType: 'image',
    enabled: true,
  },
  {
    key: 'profile',
    label: 'Profiles',
    route: '/profile',
    description: 'Creator and business profiles.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Social Bookmarking',
    route: '/sbm',
    description: 'Curated bookmarks and resources.',
    contentType: 'social',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Blog Commenting',
    route: '/blog',
    description: 'Commentary and response posts.',
    contentType: 'article',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'PDF Library',
    route: '/pdf',
    description: 'PDF resources and downloads.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Organizations',
    route: '/team',
    description: 'Organization profiles and directories.',
    contentType: 'profile',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listings',
  classified: '/classifieds',
  article: '/articles',
  image: '/image-sharing',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
